2022-03-17 20:00:00.787847: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.10.1
2022-03-17 20:00:09.000571: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2022-03-17 20:00:09.002487: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcuda.so.1
2022-03-17 20:00:09.072743: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1720] Found device 0 with properties: 
pciBusID: 0000:17:00.0 name: NVIDIA GeForce GTX 1080 Ti computeCapability: 6.1
coreClock: 1.683GHz coreCount: 28 deviceMemorySize: 10.92GiB deviceMemoryBandwidth: 451.17GiB/s
2022-03-17 20:00:09.074276: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1720] Found device 1 with properties: 
pciBusID: 0000:65:00.0 name: NVIDIA GeForce GTX 1080 Ti computeCapability: 6.1
coreClock: 1.683GHz coreCount: 28 deviceMemorySize: 10.91GiB deviceMemoryBandwidth: 451.17GiB/s
2022-03-17 20:00:09.074338: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.10.1
2022-03-17 20:00:09.313996: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublas.so.10
2022-03-17 20:00:09.314161: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublasLt.so.10
2022-03-17 20:00:09.479614: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcufft.so.10
2022-03-17 20:00:09.544454: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcurand.so.10
2022-03-17 20:00:09.773659: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcusolver.so.10
2022-03-17 20:00:09.838567: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcusparse.so.10
2022-03-17 20:00:10.334013: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudnn.so.7
2022-03-17 20:00:10.339486: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1862] Adding visible gpu devices: 0, 1
2022-03-17 20:00:10.360521: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2 AVX AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-03-17 20:00:10.692915: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1720] Found device 0 with properties: 
pciBusID: 0000:17:00.0 name: NVIDIA GeForce GTX 1080 Ti computeCapability: 6.1
coreClock: 1.683GHz coreCount: 28 deviceMemorySize: 10.92GiB deviceMemoryBandwidth: 451.17GiB/s
2022-03-17 20:00:10.693503: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1720] Found device 1 with properties: 
pciBusID: 0000:65:00.0 name: NVIDIA GeForce GTX 1080 Ti computeCapability: 6.1
coreClock: 1.683GHz coreCount: 28 deviceMemorySize: 10.91GiB deviceMemoryBandwidth: 451.17GiB/s
2022-03-17 20:00:10.693536: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.10.1
2022-03-17 20:00:10.693565: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublas.so.10
2022-03-17 20:00:10.693579: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublasLt.so.10
2022-03-17 20:00:10.693589: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcufft.so.10
2022-03-17 20:00:10.693599: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcurand.so.10
2022-03-17 20:00:10.693609: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcusolver.so.10
2022-03-17 20:00:10.693632: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcusparse.so.10
2022-03-17 20:00:10.693642: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudnn.so.7
2022-03-17 20:00:10.695489: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1862] Adding visible gpu devices: 0, 1
2022-03-17 20:00:10.747803: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.10.1
2022-03-17 20:00:15.581888: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1261] Device interconnect StreamExecutor with strength 1 edge matrix:
2022-03-17 20:00:15.581946: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1267]      0 1 
2022-03-17 20:00:15.581956: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1280] 0:   N Y 
2022-03-17 20:00:15.581961: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1280] 1:   Y N 
2022-03-17 20:00:15.596481: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1406] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10261 MB memory) -> physical GPU (device: 0, name: NVIDIA GeForce GTX 1080 Ti, pci bus id: 0000:17:00.0, compute capability: 6.1)
2022-03-17 20:00:15.631331: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1406] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:1 with 9960 MB memory) -> physical GPU (device: 1, name: NVIDIA GeForce GTX 1080 Ti, pci bus id: 0000:65:00.0, compute capability: 6.1)
2022-03-17 20:00:15.631753: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set
WARNING:tensorflow:AutoGraph could not transform <function decode at 0x7f8beb307790> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: module 'gast' has no attribute 'Index'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
WARNING:tensorflow:AutoGraph could not transform <bound method LinearLayer.call of <Layers.LinearLayer.LinearLayer object at 0x7f8be002fc40>> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: module 'gast' has no attribute 'Index'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
Epoch 1/100
2022-03-17 20:00:17.273862: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:116] None of the MLIR optimization passes are enabled (registered 2)
2022-03-17 20:00:17.327885: I tensorflow/core/platform/profile_utils/cpu_utils.cc:112] CPU Frequency: 3499910000 Hz
3668/3668 - 1758s - loss: 0.4878 - auc: 0.7676 - val_loss: 0.4808 - val_auc: 0.7738
Epoch 2/100
3668/3668 - 1753s - loss: 0.4804 - auc: 0.7739 - val_loss: 0.4803 - val_auc: 0.7741
Epoch 3/100
3668/3668 - 1738s - loss: 0.4801 - auc: 0.7741 - val_loss: 0.4802 - val_auc: 0.7741
Epoch 4/100
3668/3668 - 1733s - loss: 0.4799 - auc: 0.7741 - val_loss: 0.4801 - val_auc: 0.7741
Epoch 5/100
3668/3668 - 1733s - loss: 0.4799 - auc: 0.7742 - val_loss: 0.4801 - val_auc: 0.7741
Epoch 6/100
3668/3668 - 1710s - loss: 0.4798 - auc: 0.7742 - val_loss: 0.4801 - val_auc: 0.7741
Epoch 7/100
3668/3668 - 1776s - loss: 0.4798 - auc: 0.7743 - val_loss: 0.4801 - val_auc: 0.7741
Epoch 8/100
3668/3668 - 1723s - loss: 0.4798 - auc: 0.7743 - val_loss: 0.4801 - val_auc: 0.7741
Epoch 9/100
3668/3668 - 1792s - loss: 0.4798 - auc: 0.7743 - val_loss: 0.4801 - val_auc: 0.7741
Epoch 10/100
3668/3668 - 1919s - loss: 0.4798 - auc: 0.7743 - val_loss: 0.4801 - val_auc: 0.7741
Epoch 11/100
3668/3668 - 1843s - loss: 0.4798 - auc: 0.7743 - val_loss: 0.4801 - val_auc: 0.7741
Epoch 12/100
3668/3668 - 1817s - loss: 0.4798 - auc: 0.7743 - val_loss: 0.4801 - val_auc: 0.7741
Epoch 13/100
3668/3668 - 1913s - loss: 0.4798 - auc: 0.7743 - val_loss: 0.4801 - val_auc: 0.7741
Epoch 14/100
3668/3668 - 1783s - loss: 0.4798 - auc: 0.7743 - val_loss: 0.4801 - val_auc: 0.7741
459/459 - 211s - loss: 0.4800 - auc: 0.7740
2022-03-18 03:00:29.383595: W tensorflow/python/util/util.cc:348] Sets are not currently considered sequences, but this may change in the future, so consider avoiding using them.
